### ISSUE TITLE
[URGENT AAAAAAA] a LOT of sprites are fucked up

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1437]
haircuts, among other things
http://vgy.me/xk12nS.png facing left, really fuckin weird

facing right - looks normal http://vgy.me/xy0K9Z.png

EDIT: wtf is this? http://vgy.me/VBPdq1.png 

weed effeect fucked up too

**Comment by Spacedong** [comment]
haha fuck this shit my entire character is ruined 10/10

**Comment by Spacedong** [comment]
EDIT: also throwing things changes their sprite to be wiggly and causes a ripple effect, what hte fuck is going on

**Comment by DerptheStewpidGoat** [comment]
The bottom picture is because you have graphics hardware in your byond settings. I'm pretty certain of this because I personally encountered it at some point. In addition, the hair in the code has not been touched at all, neither have the sprites.

Chances are all these issues are because your graphics hardware in byond settings is ticked off. To enable hardware acceleration:
1. Open BYOND.
2. In the top right of the window, click on the gear, then open preferences.
3. Click on the advanced tab in the little window that pops up.
4. Check the box that says "Use graphics hardware for displaying maps (alpha-channels, anti-aliasing, etc.)

Since this issue is likely client-side because of the above-reasons, I'll be closing this unless this can be proven to not be a client-side issue.
