### ISSUE TITLE
It takes over 20 emitter shots to destroy a crate.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1503]
I'm pretty sure this is a bug, it didn't take half this long pre-rebase. I think it's even above 30 shots. I haven't tested it in a while. A few weeks ago I tried and it took really fucking long.

**Comment by danhibiki** [comment]
ITs a setting and I'll be looking into it, but this isn't a proper bug. I'll be lowering crate and closet health if I can, but probably not to pre-rebase levels because it was easy, but not leave them here because its simply ridiculous. This isn't only emitters either, which suggest closet endurance, not projectiles being weakened.
