### ISSUE TITLE
you can apparently fit an infinite amount of pills in your mouth

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1909]
title, is this intended or balancing

**Comment by Pyko1** [comment]
:3

![capture](https://cloud.githubusercontent.com/assets/12048747/13206253/ed8425d2-d902-11e5-8e5f-41b8bd6abaa8.PNG)

**Comment by Spacedong** [comment]
kek

**Comment by Pyko1** [comment]
Another issue with dental implants https://github.com/HippieStationCode/HippieStation13/issues/1891
Probably should look in to both at the same time.

**Comment by Nokington** [comment]
This is annoying

**Comment by Sarcalogo** [comment]
You can also activate them while unconscious.

**Comment by Sarcalogo** [comment]
Oh yeah, let's not forget making a pill that has reagents that reduce your stun time. This stacks by the way. You can essentially get adrenals this way.

**Comment by Sarcalogo** [comment]
Protip: Remove dental implants entirely they are unbalanced as fuck. Or put them behind a research wall or something.

**Comment by Spacedong** [comment]
stop putting everything behind a research wall, sometimes you just gotta say goodbye to a feature with this many bugs

**Comment by Sarcalogo** [comment]
You can also make implants that cause smoke reactions. So you can "suicide bomb" anyone if you're going to die anyway. It doesn't have to be explosive.

**Comment by Sarcalogo** [comment]
Let's not forget, the healing pills too! You can add multiple pills that heal all types of damage, and activate them if you are being killed. Stun immune, and you heal damage faster than you can take it.

**Comment by Sarcalogo** [comment]
Well SpaceDong buddy, to get rid of dental implants you'd just need to delete everything here starting where it says "//Dental Implants".

https://github.com/HippieStationCode/HippieStation13/blob/93a442efb6b87be7c046c94bb209c6216bee75e3/code/modules/surgery/dental_surgeries.dm

It would take you about five seconds to make the change. And then you could discuss it on the PR which people will see, instead of an issue where things are just kind of forgotten about if nobody takes a look.

**Comment by Carbonhell** [comment]
This was fixed dammith
