### ISSUE TITLE
Nuke Op ship can still be broken into even though the walls can't be deconstructed.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2056]
thermite

EDIT: they can also be apparently welder'd into and deconstructed, i thought this was fixed?

we can also maybe put a turret underneath the ship too?

**Comment by JohnGinnane** [comment]
Should it be impossible to break into the ship? I spectated someone break in through the front window and the turrets on the front couldn't shoot him

**Comment by Carbonhell** [comment]
Front window is OK but the walls should be indestructable.

**Comment by Spacedong** [comment]
imo it shouldn't be able to be broken into at all since many know all the meta locations it docks at, it's just asking to be broken into from powergamers

**Comment by trifornt-tinfornt** [comment]
Yeah, one round literally within five minutes of docking a Nuke Op reported that he saw an engineer jet past our turrets and was now welding our walls. If you don't park south then you're pretty much doomed because the back side has no turrets and it's very easy for someone to break in and take your nuke and destroy your telecomms.

**Comment by Spacedong** [comment]
scouting for nuke ops before its even confirmed should yield a warning or something, but yeah the nuke op ship should be 100% indestructable short of giant bombs or something

**Comment by Spacedong** [comment]
do the turrets even work by the way? I've never seen them fire on anyone at all

**Comment by Pyko1** [comment]
Imho it should be reinforced walls, and thermite should just be seriously nerfed when used on reinforced.

Ie. need 100 units and 60 seconds.

**Comment by Kierany9** [comment]
Rwalls are already strong enough due to how stupidly easy they are to make and how hard they are to deconstruct. Ops ship should just have indestructible walls.

But wait. What if we gave the ship its own securitron. What if we gave the ship...Dark Beepsky. Faster and stronger than Beepsky, this securitron would also lethally electrocute anybody it manages to aprehend and alert the Nuke Ops that their ship has been broken into.

**Comment by Spacedong** [comment]
how about we don't add any more features like dark beepsky that just sounds fucking edgey and terrible. just make it indestructable, takes 5 minutes, boom done

**Comment by Kierany9** [comment]
I mean the syndies already have the Dark Mauler and Dark Gygax which are already edgy af. Indestructible walls would be the most practical solution(which is what i said in the first place ree), somebody fix this already. But still...

You know you want the beepsky

**Comment by JohnGinnane** [comment]
I'll look at making the walls and windows indestructible and potential nerf for thermite

**Comment by JohnGinnane** [comment]
I seem to having some trouble opening the z2.dmm file.. It removes the locker on the syndicate's ship, the one with the disk trackers and stuff
