### ISSUE TITLE
Dental implants accept chem patches due to them being child of pills

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2080]
HOW

**Comment by JohnGinnane** [comment]
I'll look at this this evening when I'm home, but what's the issue with using a patch versus a pill? Both can only have 50 units maximum.

**Comment by meteoses** [comment]
Without antitox then patches just kill you, the only use they ever had was when you could have multiple types of patches to counter the negative effects of the patches. For instance, I've used the following implant "brute patch+burn patch+antitox-pill", but if you take out any part of that combo then you just die from the other two. If you remove the anti then you just die to the toxins, if you remove the brute patch then you die from brute damage from the burn patch, if you remove the burn patch then the inverse happens.

This is something that has already been negated via the implant limit, it is a niche thing that I personally use and taught to Cappy, but it's already negated.

**Comment by JohnGinnane** [comment]
But couldn't you use brute pills and burn pills or do patches have a different (faster?) delivery system?

**Comment by meteoses** [comment]
Nah, you could do that too, it's pretty much a non issue now imo.

**Comment by Crystalwarrior** [comment]
Still a bug, needs fixing.

**Comment by JohnGinnane** [comment]
In that case I might make it so you can only put pill type objects in teeth. Would there be any other possible items you might try to stick in your teeth?

**Comment by Pyko1** [comment]
Just make dental implant item that can hold regent container, fill it with crap and then stuff that in your mouth.

Also it would add little more effort, as you would have to construct the implant first somehow.
Also 50 units in a teeth is ridiculous when a bucket can hold 70, should be 5 or max 10.

**Comment by JohnGinnane** [comment]
But then you need to revise pills/patches and possibly even bottles. I think buckets could hold more water, and leave smaller containers.

As for the new item, do you have suggestions for how to make and and out of what materials?

**Comment by Pyko1** [comment]
Not really.

Make new item called dental_implant and only it can be implanted, and you use syringes/droppers to add reagents to them before implanting. Also define max reagents in it.

**Comment by Crystalwarrior** [comment]
Dental implants as a seperate item actually sounds like a good way to limit max volume.
Makes me wonder why did I make dental implants let you hold 50u pills in the first place, holy fuck.

**Comment by meteoses** [comment]
Pyko, have you ever considered letting a nerf sit before instantly going to compound it? I mean you just nerfed Meth, and made it so there is only 1 implant. Now you've decided to have the implants removed in order to create a new item with like 10 more steps to be able to function. 

The problem is that the patches are treated as "pills" in the code, just change that to fix the bug, don't use this as a springboard for your nerf crusade; address the bug directly instead of just saying "Oh well, I haven't looked at any solutions but let's just go with this idea of massively increased nerfs".

**Comment by Pyko1** [comment]
I havent touched meth, and im only repeating my opinion how this should had been handled on the first place. since issues remain.

**Comment by meteoses** [comment]
It's not really an issue that needs to be dealt with in such a drastic way, patches just straight up murder you if you use them, the more chemicals in it the faster you die; with only 1 patch it will have the same effect as putting cyanide into an implant then popping it: you just die. You are basically saying we should nerf a tactic that can only be used to suicide, literally, that's it, just suicide. See what my point is?

**Comment by meteoses** [comment]
The reason why I brought this up in OOC is basically just to show that I had been holding back on the community about some (FORMERLY) very powerful tactics. I only mentioned it because now that you can only have 1 implant: it can only kill you and nothing else, so I no longer needed to keep it hidden.

**Comment by Crystalwarrior** [comment]
Dental Implants were never intended to be ghetto-adrenals in the first place, they were supposed to be a last-ditch effort for a weak chemical burst in you once you got weakened or critted.
In their current state Dentals are completely fucking broken and unbalanced, heck you can make STRONGER adrenal implants using dentals, and I never intended for them to be that way.

**Comment by Pyko1** [comment]
I'm saying that implants should not hold 50 units, since a bucket is 70.
And punching a teeth out and drilling it and shit takes like extra 20 seconds or so.
Also having it as a separate item with max_reagents gives us a handy groundwork to find proper balance.

Also "my nerf crused", I don't recall nerfing shit, demanding nerfs on shit. Only trying to handle reported issues.

**Comment by blobbernaut** [comment]
tbh they should just be easier to make

just let the chemistry machine dispense a fake tooth, get rid of the access barrier and let assistants get the same ease of access to implants as the HOS by letting them use the public chem lab

that way everybody can have access to the implants, not just security, and then this wouldn't really be a huge issue

**Comment by Crystalwarrior** [comment]
Honestly I kind of like that idea more @blobbernaut

**Comment by meteoses** [comment]
The stim nerfs pretty much address the adrenaline issue, you end up paying a steep price for using one. Holding 50 chems doesn't matter, they would be adrenaline with 5 ccs or meth, they would be adrenaline with 2 ccs of meth. The implant isn't stronger than adrenaline, please stop constantly just exaggerating values, it's antithetical. Adrenaline instantly breaks all stuns and has none of the negative effects from stim chems; these lies make you look like you don't have an argument.

I too like that idea blobber, though all players do have access to make the implants since it only takes a screw driver+bedsheets, two items to which there are 50 of each on the station; you don't need a burner for most chems. Basically the pills are the only part behind a powerwall, and only the Captain/CMO/Chemists have access, not security like Blobbernaut implies, in fact security has no more access to chemistry than does any random assistant.

**Comment by Pyko1** [comment]
I think the drill is the issue here.
Maybe have the dental implant just be an option for teeth reinsert surgery.

And make a ghetto route for implant as well.

IE.
Teeth + sharp object (failchance/time) + glass + welder

**Comment by Pyko1** [comment]
Also my point is it should not hold 50 units, as that almost as much as bucket.
Even tho pretty much all the reagent_container sizes are retarded since chem is basically nerfed around it.

**Comment by meteoses** [comment]
Drill? Pyko, I already told you that a screwdriver+bedsheets is surgical drapes+drill in the code, they do the same thing, I don't use a drill, too bulky, I use a screwdriver for my implants.

**Comment by Pyko1** [comment]
well if its an item the surgery rules don't apply to making it.

**Comment by Spacedong** [comment]
@pyko screwdrivers can be used in place of drills which is pants-on-head retarded tbh

**Comment by Spacedong** [comment]
dental implants should have only 5 units and can only fit one in at a time, patches should not be able to be inserted into your mouth

**Comment by meteoses** [comment]
Patches suicide you and nothing else, not really a big deal.

5 chems is fine, no powergamer is going to mourn the loss of their 4.9 extra ccs of meth.

Screwdrivers make the implants MUCH more balanced, the more access the better.

**Comment by Pyko1** [comment]
@spacedong on surgery.

they don't just magically replace drill on attackby code.

**Comment by meteoses** [comment]
But in reality, Pyko, the do indeed work that way, check it out~

**Comment by Pyko1** [comment]
in that case there is a major error in code, it shoudl only be a substitute for surgery releated things.

**Comment by meteoses** [comment]
Dental implants are surgery, you literally have to use surgical drapes/bed sheet to start the surgery. Not sure if that's what you are talking about.

**Comment by Pyko1** [comment]
FFS, Im talking about creating an item, called dental implant, not implating it.

**Comment by Pyko1** [comment]
Basically have a separate item called dental implant that has a reagent_max and have it implanted as teeth reinsertation, hell maybe even have a chance to knock if off when hitting on mouth.

With this you don't need machinery to make pills, and its easy to balance the chem amounts.
Also if injecting chems in to it with syringe/dropper is too hard, we could add straws to bar that can be used as 1 unit droppers or so.

**Comment by meteoses** [comment]
Eh, as I've said, the limit is irrelevant, 1 cc of meth is the same as 9.9; feel free to create such a limit but I feel such an idea is misguided in that it won't achieve any effective goal.

**Comment by Pyko1** [comment]
This isn't about meth, its about dentals not supposed to have almost a bucketfull of chems in them.

**Comment by Pyko1** [comment]
Ie. you could have amix meth/omnizine/ephedrine/vitamins as well as a mix of brute/burn/toxin damage heal chems, with none of them overdosing.

**Comment by JohnGinnane** [comment]
@meteoses are saying 1 unit of meth gives the same effect for the same length of time than 5 units?

**Comment by Lawligagger** [comment]
shut up meteoses lol

**Comment by meteoses** [comment]
@JohnGinnane I'm saying that the only important effect is breaking the stun, healing chemicals and the like take too long to make, the powergamers only have time to make meth, and 1 CC of meth will break the stun. So 1 unit, 5,000 units, it's going to amount to the same thing: any units = breaks stuns.

**Comment by JohnGinnane** [comment]
Ah in that case the current limit gives you one chance at saving your skin

**Comment by meteoses** [comment]
Yep, just like the old chemical implants from the armory, nothing changed despite 2 months of nerfs.

**Comment by Pyko1** [comment]
maybe we could do
if(user.ckey == meteos)
     user.gib()

**Comment by Spacedong** [comment]
this isn't grudgecode, its a genuine issue

**Comment by Pyko1** [comment]
Anyways i find it funny "nothing changed despite 2 months of nerfs", "letting a nerf sit before instantly going to compound it" and "the limit is irrelevant".

So basically the nerf didint change anything, but we should wait to see if it changed anything instead of doing nerfs that does not really change anything?

**Comment by meteoses** [comment]
What I mean't is we are back to what we had 2 months ago, a single implant limit. I used the chemical implants back then, so it was 1 implant per person. Now again we are at 1 implant per person; see?

The nerfs did change things, I mean they literally effect the code in a manner known as "change"; but do these nerfs actually effect the way the implants are being used right now? Not at all, which is why I say it's irrelevant. 1 unit limit, 5 units, 50, it will be irrelevant since 1 unit of meth will give you a second chance.

**Comment by Carbonhell** [comment]
I don't even understand why are you guys talking about nerfing/balance on a bug report which is an obvious bug and even the one who made the code said it's a bug

**Comment by Crystalwarrior** [comment]
^^^^^
@Carbonhell meteoses is literally insane

**Comment by meteoses** [comment]
@crystalwarrior But, like, hun, my whole point at the start was that you are hijacking this to turn it into another nerf/balance "The problem is that the patches are treated as "pills" in the code, just change that to fix the bug, don't use this as a springboard for your nerf crusade; address the bug directly instead of just saying "Oh well, I haven't looked at any solutions but let's just go with this idea of massively increased nerfs"."

Maybe you are literally illiterate because he was probably talking about you guys, I made it very clear that I agree with what Carbonhell is now saying on my 3rd post.

**Comment by carlarc** [comment]
cant hijack the boat if you made it
always put a magic button that disassembles the boat in emergencies
click
lets go captain
