### ISSUE TITLE
Heads cannot be put into lockers or scanned in DNA scanners

### ISSUE THREAD

**Issue by Sarcalogo** [HippieStationCode/HippieStation13#2268]
You can't put a head in a locker, if you shut a locker on a head it just stands out. You as a consequence cannot put the head in a DNA scanner to clone it like other servers with dismemberment. You also can't put them in backpacks, which may be intentional.

**Comment by JohnGinnane** [comment]
I believe the backpack thing is intentional, to stop people beheading players and just keeping their head within the backpack. Should we be able to use the DNA scanner on all limbs? That way if you find someone's arm you could still bring them back (assuming they are dead)

**Comment by Sarcalogo** [comment]
Nah I think it should be tied to their brain.

**Comment by carlarc** [comment]
Why are heads bulky anyway? Why can't you just put it in your pack? That makes no sense.

**Comment by Crystalwarrior** [comment]
It's a balancing concern. If you could just stuff someone's dismembered head into your backpack and run around it'd basically mean easily removing someone from the round without doing a smidgeon of surgery on them.
If you really want to carry someone's brain around get an MMI and a saw.

Regarding the DNA scanner issue, it will need to have some special things done to account JUST for the heads, since right now "occupant" is required to be a living person and nothing else.

**Comment by Spacedong** [comment]
not an issue, close this
