### ISSUE TITLE
CRITICAL PRIORTY ADDRESS IMMEDIATELY

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2432]
SHADOWLINGS ARE STILL IN THE ROTATION LEASE CORRECT THIS BUG NOW

**Comment by trifornt-tinfornt** [comment]
HOLY SHIT FUCKING FIX THIS BUG IT'S URGENT AND IT'S CAUSING THE GAME TO SUCK

**Comment by Gandalf2k15** [comment]
PLEASE FIX THIS BUG THE SERVER DYING BECAUS IE IF

**Comment by nalarmg** [comment]
This is my bad. Ill update the configs to address this.

**Comment by blobbernaut** [comment]
I know admins, we have the best admins. We have the best, but there is no better admin than nalar - trump, 2016

**Comment by Hackole** [comment]
please fix it its making the game literally unplayable

**Comment by trifornt-tinfornt** [comment]
Direct quote from the game's code:
"The shadowling will seem OP, and that's because it kinda is. Being restricted to the dark while being alone most of the time is extremely difficult and as such the shadowling needs powerful abilities."
Can be found in code - game - gamemodes - shadowling - shadowling.dm

**Comment by carlarc** [comment]
what

**Comment by Carbonhell** [comment]
what? it was in rotation before too, what's the issue here

**Comment by Gandalf2k15** [comment]
Remove it

**Comment by dreamcrab** [comment]
no go away

**Comment by Gandalf2k15** [comment]
Naaah remove the shitty game mode.

**Comment by Kokojos** [comment]
Meme issue for now, you've had your fun. You know the drill, rebalance, don't remove outright,
