### ISSUE TITLE
Dominators can be placed anywhere regardless of whether the area has an APC or not.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2606]
so you get bullshit like this happening: 
https://vgy.me/O267DE.png

wow come the fuck on really

**Comment by McBawbaggings** [comment]
They should be station only.
You're trying to take over the station subsystems, doesn't make sense to be doing it off station.

**Comment by ArcLumin** [comment]
To be more specific;
To have a dominator placed, the area needs to be tagged for the gang
In order to be tagged for the gang, it must be on the station blueprints
To be on the station blueprints, an area must be airtight

This is a balancing issue where a bluespace capsule, which always shows as part of the station and is on the blueprints, is able to be tagged, and is able to be dominated.

The said screenshot was me testing my theory, then getting blown up by Spacedong, but it extends to any area you can put on blueprints, including autism forts. Putting them on the blueprints adds it to the station.

**Comment by McBawbaggings** [comment]
Or alternatively use the proc for checking if the location is on the station with the predefined list of areas.
Now this would also curb stomp building a new room but at least it prevents this shit too.

**Comment by ArcLumin** [comment]
Also, because a red alert always happens when a dom is set up by anyone, anyone can grab all 4 bluespace capsules without resulting to tricks or bugs to break them open.

**Comment by blobbernaut** [comment]
instead of having a blacklist of areas, change it to a whitelist.

**Comment by McBawbaggings** [comment]
Why I suggest using this proc:
(is_type_in_list(get_area(src), the_station_areas))

It's from commented out code on malf but it might work.
