### ISSUE TITLE
Binary Key

### ISSUE THREAD

**Issue by Swagile** [HippieStationCode/HippieStation13#3077]
Anyone with a binary key is seen as "Default Borg something something" to the AI when they speak in Binary chat.

Minor bug but it should just be "Unknown" or better yet, "Human".

Just noting this for later so I don't forget.

**Comment by ArcLumin** [comment]
This is not an issue, it's a feature. The reason it applies a fake borg name is so that the AI isn't tipped off that there's a traitor or confirms the round type because someone talks. Hell, the AI won't knowingly give up much info or will stop talking on binary radio if they know it's compromised. The only viable way to get a binary key is via traitor game mode, so it's an instant give away. Changing this would be a terrible idea, and it's not a bug.

**Comment by Swagile** [comment]
dude, an AI literally just has to click on the href of the default cyborg thing and it will realize its a human doing it, not a silicon.

plus AI knows its roundstart borgs and any borgs that get made after that, there is no way of escaping the knowledge of whether that dude that is talking on binary is a cyborg or not.

**Comment by ArcLumin** [comment]
You're overestimating the ability of an average AI to stop and pay attention.

Either way, it's intended, and not a bug
