### ISSUE TITLE
nar-sie kills cultists, harvester smoke only exists to cause lag

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#3263]

**Comment by Swagile** [comment]
nar sie is a garbage concept anyway

it removes all the reason to use all the fun abilities cultists have

ghost armies, emp rushing sec, cool bases redecorated by human cultists and constructs, blood boiling people in the halls then convert + heal, etc

all the cool shit barely gets used because the moment you have 9 people you just have to stand still for a couple of seconds and you win the round

**Comment by blobbernaut** [comment]
i agree
same principle with ascendants

**Comment by banthebantz** [comment]
tbh I kinda agree, narsie just ruins the fun for everyone.

**Comment by blobbernaut** [comment]
We should recode it as a megafauna and let the player who participated in the most sacrifices and conversions play as it.

**Comment by Spacedong** [comment]
not an issue, close this

**Comment by Spacedong** [comment]
not an issue
